# Generated by Django 2.0.5 on 2020-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started yet', 'not started yet'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='ongoing', max_length=20),
        ),
    ]
