# Generated by Django 2.0.5 on 2020-11-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='month',
        ),
    ]
